Repository Armandotrsg/ExilioGame, pull requests merged in 2023-03, with the labels that each got.

#11 Movimiento de la nave
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Player.cs
Labels: enhancement

#18 Mecánica Lateral
  Assets/Scripts/Player.cs
Labels: enhancement, Additional

#19 Crear enemigos
  Assets/Prefabs/Enemy.prefab
  Assets/Prefabs/Enemy.prefab.meta
  Assets/Prefabs/Xwing.zip/Main Camera.prefab
  Assets/Prefabs/Xwing.zip/Main Camera.prefab.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/EnemySpawn.cs
  Assets/Scripts/EnemySpawn.cs.meta
  Assets/Scripts/ParticlesMovement.cs
  Assets/Scripts/ParticlesMovement.cs.meta
  ProjectSettings/InputManager.asset
Labels: good first issue

#25 Respawn enemigo corregido, se corrigió también el error que se imprimía en consola.
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/EnemySpawn.cs
Labels: bug, invalid
